import type { Metadata } from "next";
import { Roboto, Roboto_Condensed } from 'next/font/google'
import { Providers } from "./providers";
import { DashboardLayout } from "@/components/DashboardLayout";


const roboto = Roboto({
  subsets: ['latin'],
  weight: ['400', '700'], // choose available weights
  variable: '--font-roboto', // optional for CSS custom property
  display: 'swap',
})
const roboto_condensed = Roboto_Condensed({
  subsets: ['latin'],
  weight: ['400', '700'], // choose available weights
  variable: '--font-roboto', // optional for CSS custom property
  display: 'swap',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${roboto_condensed.className} ${roboto_condensed.variable}`}>
        <Providers>
          <DashboardLayout>
            {children}
          </DashboardLayout>
        </Providers>
      </body>
    </html>
  );
}
